import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Index from '../src/pages/index'

export default function Home() {
  return (
    <div className="gradient leading-relaxed tracking-wide flex flex-col flex-1">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
    <Index />
      </main>

    </div>
  )
}
